-- ========================================
-- PEERLEARN - DATA TAMBAHAN (50+ Records)
-- File ini berisi data sample yang lebih banyak
-- Import setelah peerlearn.sql
-- ========================================

USE peerlearn;

-- DATA TUTOR TAMBAHAN (42 tutor lagi, total jadi 50)
INSERT INTO `tutor` (`nama_lengkap`, `email`, `telepon`, `keahlian`, `pendidikan`, `pengalaman_mengajar`, `harga_per_sesi`, `deskripsi`, `status`, `rating`) VALUES
('Rahman Hakim', 'rahman@example.com', '081234567898', 'Matematika', 'Institut Teknologi Bandung - Matematika', 3, 95000, 'Lulusan Matematika ITB. Spesialisasi Aljabar dan Kalkulus untuk persiapan olimpiade dan PTN.', 'Aktif', 4.8),
('Putri Ayu Lestari', 'putri.ayu@example.com', '081234567899', 'Bahasa Inggris', 'Universitas Indonesia - Sastra Inggris', 2, 85000, 'English tutor berpengalaman dengan metode communicative approach yang fun dan efektif.', 'Aktif', 4.6),
('Arif Budiman', 'arif@example.com', '081234567900', 'Fisika', 'Universitas Gadjah Mada - Fisika', 4, 100000, 'Dosen Fisika dengan pengalaman mengajar intensif untuk persiapan SBMPTN dan Olimpiade.', 'Aktif', 4.9),
('Sari Indah Permata', 'sari.indah@example.com', '081234567901', 'Kimia', 'Institut Teknologi Sepuluh Nopember - Teknik Kimia', 2, 90000, 'Mahasiswa Teknik Kimia ITS yang passionate mengajarkan kimia dengan cara yang mudah dipahami.', 'Aktif', 4.7),
('Bima Sakti', 'bima@example.com', '081234567902', 'Biologi', 'Universitas Indonesia - Biologi', 3, 88000, 'Biologist muda dengan pengalaman penelitian. Spesialisasi Genetika dan Ekologi.', 'Aktif', 4.5),
('Dewi Kartika', 'dewi.kartika@example.com', '081234567903', 'Bahasa Indonesia', 'Universitas Negeri Malang - Pend. Bahasa Indonesia', 5, 70000, 'Guru bahasa Indonesia bersertifikat dengan metode pengajaran yang kreatif dan menyenangkan.', 'Aktif', 4.6),
('Eko Prasetyo', 'eko@example.com', '081234567904', 'Ekonomi', 'Universitas Brawijaya - Ekonomi Pembangunan', 3, 82000, 'Ekonom muda dengan passion mengajar. Fokus pada ekonomi makro dan mikro untuk SMA.', 'Aktif', 4.4),
('Fitria Nurhaliza', 'fitria@example.com', '081234567905', 'Sejarah', 'Universitas Padjadjaran - Ilmu Sejarah', 2, 68000, 'Penggemar sejarah yang ingin berbagi pengetahuan dengan cara storytelling yang menarik.', 'Aktif', 4.3),
('Gilang Ramadan', 'gilang@example.com', '081234567906', 'Geografi', 'Universitas Indonesia - Geografi', 3, 75000, 'Lulusan Geografi UI. Spesialisasi geografi fisik dan lingkungan dengan metode visual learning.', 'Aktif', 4.5),
('Hana Safira', 'hana@example.com', '081234567907', 'Matematika', 'Universitas Gadjah Mada - Matematika', 4, 98000, 'Matematikawan dengan pengalaman mengajar olimpiade. Metode problem solving yang efektif.', 'Aktif', 4.8),
('Irfan Maulana', 'irfan@example.com', '081234567908', 'Fisika', 'Institut Teknologi Bandung - Fisika', 2, 92000, 'Fisikawan muda ITB. Spesialisasi mekanika dan termodinamika untuk SMA.', 'Aktif', 4.6),
('Julia Rahmawati', 'julia@example.com', '081234567909', 'Kimia', 'Universitas Indonesia - Kimia', 3, 87000, 'Chemist dengan passion teaching. Fokus kimia organik dan anorganik.', 'Aktif', 4.7),
('Kevin Wijaya', 'kevin@example.com', '081234567910', 'Bahasa Inggris', 'Binus University - English Literature', 2, 83000, 'Native-like English speaker dengan sertifikasi IELTS 8.0. Spesialisasi speaking dan writing.', 'Aktif', 4.8),
('Lisa Andriani', 'lisa@example.com', '081234567911', 'Biologi', 'Universitas Padjadjaran - Biologi', 3, 85000, 'Biologist dengan fokus pada botani dan zoologi. Metode pembelajaran berbasis eksperimen.', 'Aktif', 4.6),
('Muhammad Rizal', 'rizal@example.com', '081234567912', 'Matematika', 'Institut Teknologi Sepuluh Nopember - Matematika', 4, 96000, 'Tutor matematika berpengalaman dengan track record siswa lolos PTN favorit.', 'Aktif', 4.9),
('Nurul Fadilah', 'nurul@example.com', '081234567913', 'Bahasa Indonesia', 'Universitas Negeri Jakarta - Pend. Bahasa', 3, 72000, 'Guru bahasa Indonesia yang ramah dan sabar. Spesialisasi sastra dan tata bahasa.', 'Aktif', 4.5),
('Omar Abdullah', 'omar@example.com', '081234567914', 'Ekonomi', 'Universitas Airlangga - Ekonomi', 2, 80000, 'Fresh graduate ekonomi dengan IPK cumlaude. Passionate mengajar ekonomi mikro dan makro.', 'Aktif', 4.4),
('Puspita Sari', 'puspita@example.com', '081234567915', 'Fisika', 'Universitas Brawijaya - Fisika', 3, 90000, 'Fisikawan dengan metode pembelajaran visual dan praktis. Spesialisasi elektromagnetisme.', 'Aktif', 4.7),
('Qori Aulia', 'qori@example.com', '081234567916', 'Kimia', 'Institut Teknologi Bandung - Kimia', 2, 89000, 'Mahasiswa Kimia ITB dengan prestasi akademik tinggi. Fokus kimia dasar hingga lanjut.', 'Aktif', 4.6),
('Rendi Saputra', 'rendi@example.com', '081234567917', 'Sejarah', 'Universitas Indonesia - Sejarah', 3, 70000, 'Sejarawan muda dengan metode pembelajaran berbasis cerita dan visualisasi.', 'Aktif', 4.4),
('Siti Nurjanah', 'siti@example.com', '081234567918', 'Bahasa Inggris', 'Universitas Negeri Yogyakarta - Pend. Bahasa Inggris', 4, 86000, 'English teacher bersertifikat dengan pengalaman mengajar TOEFL dan IELTS.', 'Aktif', 4.8),
('Taufik Hidayat', 'taufik@example.com', '081234567919', 'Matematika', 'Universitas Gadjah Mada - Matematika', 3, 94000, 'Tutor matematika dengan metode quick learning. Spesialisasi trigonometri dan kalkulus.', 'Aktif', 4.7),
('Umi Kalsum', 'umi@example.com', '081234567920', 'Biologi', 'Institut Pertanian Bogor - Biologi', 2, 84000, 'Biologist IPB dengan fokus ekologi dan genetika. Pembelajaran berbasis riset.', 'Aktif', 4.5),
('Vera Octavia', 'vera@example.com', '081234567921', 'Geografi', 'Universitas Padjadjaran - Geografi', 3, 74000, 'Geographer dengan passion lingkungan. Metode pembelajaran field study dan mapping.', 'Aktif', 4.4),
('Wahyu Setiawan', 'wahyu@example.com', '081234567922', 'Ekonomi', 'Universitas Indonesia - Ilmu Ekonomi', 4, 88000, 'Ekonom berpengalaman dengan fokus ekonomi pembangunan dan moneter.', 'Aktif', 4.7),
('Xena Maharani', 'xena@example.com', '081234567923', 'Fisika', 'Institut Teknologi Bandung - Fisika Nuklir', 2, 93000, 'Fisikawan nuklir dengan kemampuan menjelaskan konsep kompleks dengan sederhana.', 'Aktif', 4.6),
('Yoga Pratama', 'yoga@example.com', '081234567924', 'Kimia', 'Universitas Gadjah Mada - Kimia', 3, 86000, 'Chemist dengan spesialisasi kimia analitik dan farmasi. Metode praktis dan aplikatif.', 'Aktif', 4.5),
('Zahra Amelia', 'zahra@example.com', '081234567925', 'Matematika', 'Institut Teknologi Sepuluh Nopember - Matematika Terapan', 4, 97000, 'Matematikawan terapan dengan pengalaman mengajar intensif untuk olimpiade dan PTN.', 'Aktif', 4.9),
('Angga Permana', 'angga@example.com', '081234567926', 'Bahasa Inggris', 'Universitas Indonesia - Linguistics', 3, 84000, 'Linguist dengan fokus English for Academic Purposes. TOEFL 110+.', 'Aktif', 4.7),
('Bella Safitri', 'bella@example.com', '081234567927', 'Biologi', 'Universitas Brawijaya - Biologi', 2, 82000, 'Biologist muda dengan metode pembelajaran interaktif dan fun learning.', 'Aktif', 4.5),
('Candra Kusuma', 'candra@example.com', '081234567928', 'Sejarah', 'Universitas Padjadjaran - Pendidikan Sejarah', 3, 69000, 'Guru sejarah yang menggunakan multimedia dan storytelling dalam pembelajaran.', 'Aktif', 4.4),
('Diana Putri', 'diana@example.com', '081234567929', 'Bahasa Indonesia', 'Universitas Negeri Jakarta - Sastra Indonesia', 4, 73000, 'Ahli sastra Indonesia dengan metode pembelajaran kreatif dan apresiatif.', 'Aktif', 4.6),
('Erick Firmansyah', 'erick@example.com', '081234567930', 'Matematika', 'Universitas Indonesia - Matematika', 3, 95000, 'Matematikawan UI dengan pengalaman coaching olimpiade matematika tingkat nasional.', 'Aktif', 4.8),
('Fani Rahmawati', 'fani@example.com', '081234567931', 'Fisika', 'Institut Teknologi Bandung - Fisika', 2, 91000, 'Fisikawan ITB dengan metode pembelajaran problem-based learning yang efektif.', 'Aktif', 4.6),
('Gita Savitri', 'gita@example.com', '081234567932', 'Kimia', 'Universitas Gadjah Mada - Kimia Murni', 3, 88000, 'Chemist UGM dengan spesialisasi kimia organik. Pembelajaran berbasis eksperimen.', 'Aktif', 4.7),
('Hendra Gunawan', 'hendra@example.com', '081234567933', 'Ekonomi', 'Institut Pertanian Bogor - Ekonomi Pertanian', 2, 78000, 'Ekonom pertanian dengan pemahaman ekonomi mikro dan makro yang kuat.', 'Aktif', 4.4),
('Intan Permatasari', 'intan@example.com', '081234567934', 'Bahasa Inggris', 'Binus University - English Literature', 4, 87000, 'English tutor dengan sertifikasi Cambridge. Spesialisasi grammar dan vocabulary building.', 'Aktif', 4.8),
('Joko Susilo', 'joko@example.com', '081234567935', 'Geografi', 'Universitas Gadjah Mada - Geografi', 3, 76000, 'Geographer UGM dengan fokus pada geografi regional dan pemetaan.', 'Aktif', 4.5),
('Kartika Dewi', 'kartika@example.com', '081234567936', 'Biologi', 'Universitas Indonesia - Biologi', 2, 83000, 'Biologist UI dengan spesialisasi mikrobiologi dan bioteknologi.', 'Aktif', 4.6),
('Lutfi Rahman', 'lutfi@example.com', '081234567937', 'Matematika', 'Institut Teknologi Bandung - Matematika Diskrit', 4, 99000, 'Ahli matematika diskrit dengan pengalaman mengajar competitive programming.', 'Aktif', 4.9),
('Melati Kusuma', 'melati@example.com', '081234567938', 'Fisika', 'Universitas Padjadjaran - Fisika', 3, 89000, 'Fisikawan dengan metode pembelajaran demonstrasi dan simulasi interaktif.', 'Aktif', 4.6),
('Novan Ardiansyah', 'novan@example.com', '081234567939', 'Kimia', 'Institut Teknologi Sepuluh Nopember - Kimia', 2, 85000, 'Chemist ITS dengan fokus kimia industri dan lingkungan. Pembelajaran aplikatif.', 'Aktif', 4.5);

-- DATA SISWA TAMBAHAN (47 siswa lagi, total jadi 50)
INSERT INTO `siswa` (`nim`, `nama_lengkap`, `email`, `jenjang`, `sekolah`, `kelas`, `minat`, `status`) VALUES
('2021004', 'Eka Putri', 'eka.putri@example.com', 'SMA', 'SMA Negeri 3 Bandar Lampung', '10 IPA 2', 'Biologi, Kimia', 'Aktif'),
('2021005', 'Fajar Nugroho', 'fajar@example.com', 'SMP', 'SMP Negeri 1 Bandar Lampung', '8B', 'Matematika, IPA', 'Aktif'),
('2021006', 'Gina Rahmawati', 'gina@example.com', 'SMA', 'SMA Negeri 4 Bandar Lampung', '11 IPA 1', 'Fisika, Matematika', 'Aktif'),
('2021007', 'Hadi Wijaya', 'hadi@example.com', 'SMA', 'SMA Negeri 5 Bandar Lampung', '12 IPS 1', 'Ekonomi, Geografi', 'Aktif'),
('2021008', 'Indah Permata', 'indah@example.com', 'SMP', 'SMP Negeri 2 Bandar Lampung', '9B', 'Bahasa Inggris, Matematika', 'Aktif'),
('2021009', 'Jihan Aulia', 'jihan@example.com', 'SMA', 'SMA Negeri 1 Bandar Lampung', '10 IPA 1', 'Kimia, Biologi', 'Aktif'),
('2021010', 'Krisna Mukti', 'krisna@example.com', 'SMA', 'SMA Negeri 2 Bandar Lampung', '11 IPA 3', 'Matematika, Fisika', 'Aktif'),
('2021011', 'Laila Sari', 'laila@example.com', 'SMP', 'SMP Negeri 3 Bandar Lampung', '7A', 'IPA, Matematika', 'Aktif'),
('2021012', 'Mario Putra', 'mario@example.com', 'SMA', 'SMA Negeri 6 Bandar Lampung', '12 IPA 2', 'Fisika, Matematika', 'Aktif'),
('2021013', 'Nina Kurniawati', 'nina@example.com', 'SMP', 'SMP Negeri 4 Bandar Lampung', '8A', 'Bahasa Indonesia, IPS', 'Aktif'),
('2021014', 'Oscar Raharjo', 'oscar@example.com', 'SMA', 'SMA Negeri 3 Bandar Lampung', '11 IPS 2', 'Sejarah, Ekonomi', 'Aktif'),
('2021015', 'Putri Wulandari', 'putri.w@example.com', 'SMA', 'SMA Negeri 7 Bandar Lampung', '10 IPA 3', 'Biologi, Kimia', 'Aktif'),
('2021016', 'Qomar Syarif', 'qomar@example.com', 'SMP', 'SMP Negeri 5 Bandar Lampung', '9C', 'Matematika, IPA', 'Aktif'),
('2021017', 'Rina Susanti', 'rina@example.com', 'SMA', 'SMA Negeri 1 Bandar Lampung', '12 IPA 3', 'Kimia, Fisika', 'Aktif'),
('2021018', 'Sandi Pratama', 'sandi@example.com', 'SMA', 'SMA Negeri 4 Bandar Lampung', '11 IPA 2', 'Matematika, Fisika', 'Aktif'),
('2021019', 'Tina Marlina', 'tina@example.com', 'SMP', 'SMP Negeri 1 Bandar Lampung', '8C', 'Bahasa Inggris, IPA', 'Aktif'),
('2021020', 'Umar Bakri', 'umar@example.com', 'SMA', 'SMA Negeri 5 Bandar Lampung', '10 IPS 1', 'Ekonomi, Sejarah', 'Aktif'),
('2021021', 'Vina Octavia', 'vina@example.com', 'SMA', 'SMA Negeri 2 Bandar Lampung', '12 IPS 2', 'Geografi, Ekonomi', 'Aktif'),
('2021022', 'Wawan Setiawan', 'wawan@example.com', 'SMP', 'SMP Negeri 2 Bandar Lampung', '7B', 'Matematika, IPA', 'Aktif'),
('2021023', 'Yuli Astuti', 'yuli@example.com', 'SMA', 'SMA Negeri 6 Bandar Lampung', '11 IPA 1', 'Biologi, Kimia', 'Aktif'),
('2021024', 'Zaki Abdullah', 'zaki@example.com', 'SMP', 'SMP Negeri 3 Bandar Lampung', '9A', 'Matematika, Fisika', 'Aktif'),
('2021025', 'Aditya Pratama', 'aditya.p@example.com', 'SMA', 'SMA Negeri 3 Bandar Lampung', '10 IPA 1', 'Fisika, Matematika', 'Aktif'),
('2021026', 'Bunga Citra', 'bunga@example.com', 'SMA', 'SMA Negeri 1 Bandar Lampung', '12 IPA 1', 'Kimia, Biologi', 'Aktif'),
('2021027', 'Cahya Nugraha', 'cahya@example.com', 'SMP', 'SMP Negeri 4 Bandar Lampung', '8B', 'IPA, Bahasa Inggris', 'Aktif'),
('2021028', 'Dinda Amelia', 'dinda@example.com', 'SMA', 'SMA Negeri 7 Bandar Lampung', '11 IPS 1', 'Ekonomi, Geografi', 'Aktif'),
('2021029', 'Eko Saputra', 'eko.s@example.com', 'SMA', 'SMA Negeri 4 Bandar Lampung', '10 IPA 2', 'Matematika, Fisika', 'Aktif'),
('2021030', 'Fira Maharani', 'fira@example.com', 'SMP', 'SMP Negeri 1 Bandar Lampung', '9B', 'Bahasa Indonesia, IPS', 'Aktif'),
('2021031', 'Galih Pratama', 'galih@example.com', 'SMA', 'SMA Negeri 5 Bandar Lampung', '12 IPA 2', 'Fisika, Kimia', 'Aktif'),
('2021032', 'Hani Fadilah', 'hani@example.com', 'SMA', 'SMA Negeri 2 Bandar Lampung', '11 IPA 1', 'Biologi, Kimia', 'Aktif'),
('2021033', 'Irvan Maulana', 'irvan@example.com', 'SMP', 'SMP Negeri 5 Bandar Lampung', '7C', 'Matematika, IPA', 'Aktif'),
('2021034', 'Jasmine Putri', 'jasmine@example.com', 'SMA', 'SMA Negeri 6 Bandar Lampung', '10 IPA 3', 'Bahasa Inggris, Biologi', 'Aktif'),
('2021035', 'Karina Salsabila', 'karina@example.com', 'SMA', 'SMA Negeri 3 Bandar Lampung', '12 IPS 1', 'Sejarah, Ekonomi', 'Aktif'),
('2021036', 'Luthfi Hakim', 'luthfi@example.com', 'SMP', 'SMP Negeri 2 Bandar Lampung', '8A', 'IPA, Matematika', 'Aktif'),
('2021037', 'Mira Rahayu', 'mira@example.com', 'SMA', 'SMA Negeri 1 Bandar Lampung', '11 IPA 2', 'Kimia, Fisika', 'Aktif'),
('2021038', 'Nanda Permana', 'nanda@example.com', 'SMA', 'SMA Negeri 7 Bandar Lampung', '10 IPS 2', 'Ekonomi, Geografi', 'Aktif'),
('2021039', 'Olivia Wijaya', 'olivia@example.com', 'SMP', 'SMP Negeri 3 Bandar Lampung', '9C', 'Bahasa Inggris, IPA', 'Aktif'),
('2021040', 'Pandu Wicaksono', 'pandu@example.com', 'SMA', 'SMA Negeri 4 Bandar Lampung', '12 IPA 1', 'Matematika, Fisika', 'Aktif'),
('2021041', 'Qonita Rahmawati', 'qonita@example.com', 'SMA', 'SMA Negeri 5 Bandar Lampung', '11 IPA 3', 'Biologi, Kimia', 'Aktif'),
('2021042', 'Raka Firmansyah', 'raka@example.com', 'SMP', 'SMP Negeri 4 Bandar Lampung', '7A', 'Matematika, IPA', 'Aktif'),
('2021043', 'Salma Azzahra', 'salma@example.com', 'SMA', 'SMA Negeri 2 Bandar Lampung', '10 IPA 1', 'Fisika, Matematika', 'Aktif'),
('2021044', 'Tegar Saputra', 'tegar@example.com', 'SMA', 'SMA Negeri 6 Bandar Lampung', '12 IPS 2', 'Ekonomi, Sejarah', 'Aktif'),
('2021045', 'Ulfa Rahmawati', 'ulfa@example.com', 'SMP', 'SMP Negeri 1 Bandar Lampung', '8B', 'Bahasa Indonesia, IPS', 'Aktif'),
('2021046', 'Vino Mahendra', 'vino@example.com', 'SMA', 'SMA Negeri 3 Bandar Lampung', '11 IPA 2', 'Kimia, Biologi', 'Aktif'),
('2021047', 'Wulan Dari', 'wulan@example.com', 'SMA', 'SMA Negeri 1 Bandar Lampung', '10 IPS 1', 'Geografi, Ekonomi', 'Aktif'),
('2021048', 'Yusuf Rahman', 'yusuf@example.com', 'SMP', 'SMP Negeri 5 Bandar Lampung', '9A', 'Matematika, IPA', 'Aktif'),
('2021049', 'Zainal Abidin', 'zainal@example.com', 'SMA', 'SMA Negeri 7 Bandar Lampung', '12 IPA 3', 'Fisika, Kimia', 'Aktif'),
('2021050', 'Alya Safitri', 'alya@example.com', 'SMA', 'SMA Negeri 4 Bandar Lampung', '11 IPA 1', 'Biologi, Matematika', 'Aktif');

SELECT 'Data tambahan berhasil diimport! Total 50 tutor dan 50 siswa.' AS status;
